#spring.application.name=online

spring:
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
api:
  endpoint:
    base-url: /api/v1
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, env, beans, configprops, heapdump, httpexchanges, loggers, mappings, custom-beans
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    env:
      show-values: always
    configprops:
      show-values: always
  info:
    build:
      enabled: true
    env:
      enabled: true
    git:
      enabled: true
      mode: full
    java:
      enabled: true
    os:
      enabled: true
info:
  app:
    name: hogwarts-artifact-online
    description: A web application that manages artifacts and wizards for Hogwarts School
    version: @project.version@
    author: Christopher Lijoodi
    links:
      youtube: https://youtube.com
      github: https://github.com/chrizlm/Hogwarts